import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType
} from "docx";
import type { EventReadinessEventRequest } from "../schemas/eventReadiness.js";
import { buildEisDraft } from "./eisDraftService.js";
import { normaliseEventRequestFinanceCode } from "./financeCodeService.js";
import { assessPostPhase1KeyEvent } from "./postPhase1KeyEventService.js";

function cell(children: Paragraph[], width: number) {
  return new TableCell({
    width: { size: width, type: WidthType.PERCENTAGE },
    children
  });
}

function paragraph(text: string, bold = false) {
  return new Paragraph({
    children: [new TextRun({ text, bold })]
  });
}

export async function buildEisDocx(eventRequest: EventReadinessEventRequest) {
  const normalisedEventRequest = normaliseEventRequestFinanceCode(eventRequest);
  const keyEvent = assessPostPhase1KeyEvent(normalisedEventRequest);
  const eis = buildEisDraft(normalisedEventRequest, keyEvent);
  const rows = Object.values(eis.fields).map(
    (field) =>
      new TableRow({
        children: [
          cell([paragraph(field.label, true)], 35),
          cell([paragraph(field.status === "needs_confirmation" ? `Needs confirmation: ${field.value}` : field.value)], 65)
        ]
      })
  );

  const children: Array<Paragraph | Table> = [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      alignment: AlignmentType.CENTER,
      children: [new TextRun("LBS Event Information Sheet Draft")]
    }),
    new Paragraph({
      alignment: AlignmentType.CENTER,
      children: [new TextRun({ text: "Generated by the Event Readiness Assistant. This draft has not been submitted automatically.", italics: true })]
    }),
    new Paragraph({ text: "" }),
    paragraph(eis.reason, true)
  ];

  if (rows.length > 0) {
    children.push(
      new Paragraph({ text: "" }),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows
      })
    );
  } else {
    children.push(new Paragraph({ text: "No EIS content is required for this event based on the current deterministic Key Event assessment." }));
  }

  const document = new Document({
    sections: [{ children }]
  });

  return Packer.toBuffer(document);
}
