import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  Table,
  TableCell,
  TableRow,
  TextRun,
  WidthType
} from "docx";
import type { EventReadinessEventRequest, FieldStatus } from "../schemas/eventReadiness.js";
import { getSpaceRequestFields } from "./eventReadinessService.js";

const uncertaintyStatuses = new Set<FieldStatus>([
  "best_estimate",
  "not_sure_yet",
  "needs_confirmation",
  "organiser_follow_up",
  "missing"
]);

function fieldValue(eventRequest: EventReadinessEventRequest, key: string) {
  const value = eventRequest.fields[key];
  if (value === null || value === undefined || value === "") return "";
  if (typeof value === "string") return value;
  return String(value);
}

function displayStatus(status: FieldStatus | undefined) {
  if (!status || status === "final") return "";
  return status
    .split("_")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

function cell(children: Paragraph[], width: number) {
  return new TableCell({
    width: { size: width, type: WidthType.PERCENTAGE },
    children
  });
}

function labelParagraph(text: string) {
  return new Paragraph({
    children: [new TextRun({ text, bold: true })]
  });
}

function valueParagraph(value: string, status: FieldStatus | undefined) {
  const statusLabel = displayStatus(status);
  const needsMarker = status && uncertaintyStatuses.has(status);
  return new Paragraph({
    children: [
      ...(needsMarker && statusLabel ? [new TextRun({ text: `${statusLabel}: `, bold: true, color: "B00020" })] : []),
      new TextRun(value || "Not provided")
    ]
  });
}

export async function buildSpaceRequestDocx(eventRequest: EventReadinessEventRequest) {
  const rows = getSpaceRequestFields().map((field) => {
    const status = eventRequest.field_status[field.key];
    return new TableRow({
      children: [
        cell([labelParagraph(field.label), new Paragraph({ children: [new TextRun({ text: field.category, italics: true })] })], 35),
        cell([valueParagraph(fieldValue(eventRequest, field.key), status)], 65)
      ]
    });
  });

  const document = new Document({
    sections: [
      {
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            alignment: AlignmentType.CENTER,
            children: [new TextRun("LBS Space Request Draft")]
          }),
          new Paragraph({
            alignment: AlignmentType.CENTER,
            children: [
              new TextRun({
                text: "Generated by the Event Readiness Assistant. This draft has not been submitted automatically.",
                italics: true
              })
            ]
          }),
          new Paragraph({ text: "" }),
          new Table({
            width: { size: 100, type: WidthType.PERCENTAGE },
            rows
          })
        ]
      }
    ]
  });

  return Packer.toBuffer(document);
}
